# Generated by Django 4.2.6 on 2023-10-30 06:30

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to=accounts.models.user_directory_path, verbose_name='프로필 사진'),
        ),
    ]
